'use strict';

// tests for parking
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('parking', '/handler.js', 'parking');

describe('parking', () => {
  before((done) => {
    done();
  });

  it('implement tests here', async () => {
    var event = {queryStringParameters:{date:'2020-10-11'}};
    const response = await wrapped.run(event);
    expect(response).to.not.be.empty;
  });

  it('not empty and 200', async () => {
    var event = {queryStringParameters:{date:'2020-10-11'}};
    const response = await wrapped.run(event);
    expect(response).to.not.be.empty;
    expect(response.statusCode).to.be.equal(200);
  });
});
